name: ERDFFD
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
    inputs:
      bu:
        required: false
        type: string
      version_to_deploy:
        required: false
        type: string
  
jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/reusable.yml
    with:
      bu: ${{inputs.bu}}
      version_to_deploy: ${{inputs.version_to_deploy}}
      
