name: ERDFFD
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
  
jobs:
  deploy-uat-lmfr:
    name: UAT LMFR
    uses: ./.github/workflows/reusable.yml
    with:
      bu: ${{inputs.bu}}
      version_to_deploy: ${{inputs.version_to_deploy}}
      
