name: 🤖 Deploy TEST

on:
  workflow_dispatch:
    inputs:
      bu:
        required: true
        type: string
      version_to_deploy:
        required: true
        type: string

jobs:
  publish_release:
    runs-on: [ Linux, standard ]
    steps:
      - name: Send custom test
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

