name: Environment Configuration Workflow

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        required: true
        description: 'Choose environment'
        options:
          - DEV
          - STAGING
          - PROD

jobs:
  set-env:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - env: DEV
            apikey_path: "path/dev/to"
            business_units: '["bu1", "bu2"]'
            contexts: '["sit"]'
          - env: STAGING
            apikey_path: "path/uat/to"
            business_units: '["bu1", "bu3"]'
            contexts: '["uat", "pprod"]'
          - env: PROD
            apikey_path: "path/prod/to"
            business_units: '["bu2", "bu3"]'
            contexts: '["prod"]'

    outputs:
      env: ${{ steps.set_output.outputs.env }}
      apikey_path: ${{ steps.set_output.outputs.apikey_path }}
      environments: ${{ steps.set_output.outputs.environments }}
      contexts: ${{ steps.set_output.outputs.contexts }}
    steps:
      - name: Setup Environment
        if: ${{ matrix.env == github.event.inputs.env }}
        run: |
          echo "Setting up environment for ${{ matrix.env }}"
          echo "ENV=${{ matrix.env }}" >> $GITHUB_OUTPUT
          echo "APIKEY_PATH=${{ matrix.apikey_path }}" >> $GITHUB_OUTPUT
          echo "BUSINESS_UNITS=${{ matrix.business_units }}" >> $GITHUB_OUTPUT
          echo "CONTEXTS=${{ matrix.contexts }}" >> $GITHUB_OUTPUT
        id: set_output

  echo-env:
    needs: set-env
    runs-on: ubuntu-latest
    if: ${{ needs.set-env.outputs.env == github.event.inputs.env }}
    steps:
      - name: Echo Environment Configuration
        run: |
          echo "Environment: ${{ needs.set-env.outputs.env }}"
          echo "API Key Path: ${{ needs.set-env.outputs.apikey_path }}"
          echo "Environments: ${{ needs.set-env.outputs.environments }}"
          echo "Contexts: ${{ needs.set-env.outputs.contexts }}"

