name: Deploy DEV (Simulation)

on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: [self-hosted, Linux, standard]

    outputs:
      version_to_deploy: ${{ steps.version.outputs.VERSION_TO_DEPLOY }}
      changed_files: ${{ steps.get_changes.outputs.changed_files }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Get changed files
        id: get_changes
        run: |
          git diff --name-only HEAD^ HEAD > changed_files.txt
          echo "::set-output name=changed_files::$(cat changed_files.txt)"

  simulate_push_jfrog:
    needs: prepare
    strategy:
      matrix:
        name: ['api', 'docs']
          
    name: Simulate build and push for ${{ matrix.name }}
    runs-on: ubuntu-latest

    steps:
      - name: Set service paths
        id: set_paths
        run: |
          if [ "${{ matrix.name }}" == "api" ]; then
            echo "::set-output name=service_path::./api/"
          elif [ "${{ matrix.name }}" == "docs" ]; then
            echo "::set-output name=service_path::./docs/"
          fi

      - name: Check if service was modified
        id: check_modifications
        run: |
          if grep -q "${{ steps.set_paths.outputs.service_path }}" <<< "${{ needs.prepare.outputs.changed_files }}"; then
            echo "Changes detected for ${{ matrix.name }}"
            echo "::set-output name=should_deploy::true"
          else
            echo "No changes detected for ${{ matrix.name }}"
            echo "::set-output name=should_deploy::false"
          fi

      - name: Simulate building Docker image
        if: steps.check_modifications.outputs.should_deploy == 'true'
        run: |
          echo "Building Docker image for ${{ matrix.name }}"
          echo "This would execute: docker build -f ./apps/${{ matrix.name }}/Dockerfile ."
      
      - name: Simulate pushing Docker image to JFrog
        if: steps.check_modifications.outputs.should_deploy == 'true'
        run: |
          echo "Simulating push of Docker image for ${{ matrix.name }} to Docker"
          echo "Image name: ${{ matrix.name }}"
          echo "Repository: docker"
