name: Deploy DEV (Simulation)

on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest

    outputs:
      version_to_deploy: ${{ steps.version.outputs.VERSION_TO_DEPLOY }}
      changed_files: ${{ steps.get_changes.outputs.changed_files }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Get changed files
        id: get_changes
        run: |
          git diff --name-only HEAD^ HEAD > changed_files.txt
          echo "changed_files=$(cat changed_files.txt)" >> $GITHUB_ENV

  simulate_push_jfrog:
    needs: prepare
    strategy:
      matrix:
        name: ['api', 'docs']
          
    name: Simulate build and push for ${{ matrix.name }}
    runs-on: ubuntu-latest

    steps:
      - name: Set service paths
        id: set_paths
        run: |
          if [ "${{ matrix.name }}" == "api" ]; then
            echo "service_path=api/" >> $GITHUB_ENV
          elif [ "${{ matrix.name }}" == "docs" ]; then
            echo "service_path=docs/" >> $GITHUB_ENV
          fi

      - name: Check if service was modified
        id: check_modifications
        run: |
          if grep -q "^${service_path}" <<< "${{ needs.prepare.outputs.changed_files }}"; then
            echo "Changes detected for ${{ matrix.name }}"
            echo "should_deploy=true" >> $GITHUB_ENV
          else
            echo "No changes detected for ${{ matrix.name }}"
            echo "should_deploy=false" >> $GITHUB_ENV
        env:
          service_path: ${{ steps.set_paths.outputs.service_path }}

      - name: Simulate building Docker image
        if: env.should_deploy == 'true'
        run: |
          echo "Building Docker image for ${{ matrix.name }}"
          echo "This would execute: docker build -f ./apps/${{ matrix.name }}/Dockerfile ."
      
      - name: Simulate pushing Docker image to JFrog
        if: env.should_deploy == 'true'
        run: |
          echo "Simulating push of Docker image for ${{ matrix.name }} to Docker"
          echo "Image name: ${{ matrix.name }}"
          echo "Repository: docker"
